import { FormGroupType } from '../../../interfaces/form-group-type'
import { Ability } from '../../abilities/interfaces/i-abilities'

export interface ISkill {
    name: Skill
    keyAbility: Ability
    skillModifier: number
    abilityModifier: number
    ranks: number
    miscModifier: number
    isClassSkill: boolean
    isTrainedOnly: boolean
    specialisation: string | null
}

export type ISkillForm = FormGroupType<ISkill>

export const Skill = {
    APPRAISE: 'Appraise',
    BALANCE: 'Balance',
    BLUFF: 'Bluff',
    CLIMB: 'Climb',
    CONCENTRATION: 'Concentration',
    CRAFT: 'Craft',
    DECIPHER_SCRIPT: 'Decipher Script',
    DIPLOMACY: 'Diplomacy',
    DISABLE_DEVICE: 'Disable Device',
    DISGUISE: 'Disguise',
    ESCAPE_ARTIST: 'Escape Artist',
    FORGERY: 'Forgery',
    GATHER_INFORMATION: 'Gather Information',
    HANDLE_ANIMAL: 'Handle Animal',
    HEAL: 'Heal',
    HIDE: 'Hide',
    INTIMIDATE: 'Intimidate',
    JUMP: 'Jump',
    KNOWLEDGE: 'Knowledge',
    LISTEN: 'Listen',
    MOVE_SILENTLY: 'Move Silently',
    OPEN_LOCK: 'Open Lock',
    PERFORM: 'Perform',
    PROFESSION: 'Profession',
    RIDE: 'Ride',
    SEARCH: 'Search',
    SENSE_MOTIVE: 'Sense Motive',
    SLEIGHT_OF_HAND: 'Sleight of Hand',
    SPELLCRAFT: 'Spellcraft',
    SPOT: 'Spot',
    SURVIVAL: 'Survival',
    SWIM: 'Swim',
    TUMBLE: 'Tumble',
    USE_MAGIC_DEVICE: 'Use Magic Device',
    USE_ROPE: 'Use Rope',
    OTHER: 'Other',
} as const
export type Skill = (typeof Skill)[keyof typeof Skill]

export const initialSkillState: ISkill[] = [
    {
        name: Skill.APPRAISE,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.BALANCE,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.BLUFF,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.CLIMB,
        keyAbility: Ability.STRENGTH,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.CONCENTRATION,
        keyAbility: Ability.CONSTITUTION,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.CRAFT,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: '',
    },
    {
        name: Skill.DECIPHER_SCRIPT,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.DIPLOMACY,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.DISABLE_DEVICE,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.DISGUISE,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.ESCAPE_ARTIST,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.FORGERY,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.GATHER_INFORMATION,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.HANDLE_ANIMAL,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.HEAL,
        keyAbility: Ability.WISDOM,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.HIDE,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.INTIMIDATE,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.JUMP,
        keyAbility: Ability.STRENGTH,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.KNOWLEDGE,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: '',
    },
    {
        name: Skill.LISTEN,
        keyAbility: Ability.WISDOM,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.MOVE_SILENTLY,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.OPEN_LOCK,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.PERFORM,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: '',
    },
    {
        name: Skill.PROFESSION,
        keyAbility: Ability.WISDOM,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: '',
    },
    {
        name: Skill.RIDE,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.SEARCH,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.SENSE_MOTIVE,
        keyAbility: Ability.WISDOM,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.SLEIGHT_OF_HAND,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.SPELLCRAFT,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.SPOT,
        keyAbility: Ability.WISDOM,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.SURVIVAL,
        keyAbility: Ability.WISDOM,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.SWIM,
        keyAbility: Ability.STRENGTH,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.TUMBLE,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.USE_MAGIC_DEVICE,
        keyAbility: Ability.CHARISMA,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: true,
        specialisation: null,
    },
    {
        name: Skill.USE_ROPE,
        keyAbility: Ability.DEXTERITY,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: null,
    },
    {
        name: Skill.OTHER,
        keyAbility: Ability.INTELLIGENCE,
        skillModifier: 0,
        abilityModifier: 0,
        ranks: 0,
        miscModifier: 0,
        isClassSkill: false,
        isTrainedOnly: false,
        specialisation: '',
    },
]
